### ISSUE TITLE
Compatible version  for Laravel 5.2

### ISSUE THREAD

**Issue by ZRktty** [TheDoctor0/laravel-mailjet-driver#8]
I tried installing the 0.1 version with no success.

![image](https://user-images.githubusercontent.com/6025181/196035145-44c368d8-5b4f-47b4-9409-7710c98510dd.png)

**Comment by TheDoctor0** [comment]
Hey @zr87.
Looks like that is because of `mailjet/mailjet-swiftmailer` that requires `symfony/mailjet-mailer^6.0`.
Based on that I can say that it no longer supports Laravel below version 5.5, so if possible you need to upgrade to it.
