### ISSUE TITLE
Inline attachments don't work

### ISSUE THREAD

**Issue by dicaccamovincenzo92** [TheDoctor0/laravel-mailjet-driver#9]
Hi,
using ` $message->embed($pathToFile);` to embed an inline attached image, results in empty img tag on received email.
Is there any workaround? Could you add inline attachment compatibility to this package?

**Comment by TheDoctor0** [comment]
Hey @dicaccamovincenzo92.
This package is only a Laravel wrapper, so if you have an issue with the inline attachment I suggest reporting that at https://github.com/symfony/mailjet-mailer.
